### ISSUE TITLE
Story telling Feature

### ISSUE THREAD

**Issue by ShashankVenkatramani** [cse110-sp23-group16/cse110-sp23-group16#105]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

For this feature we want to take the constellation page and make it more akin to a storytelling format, rather than showing them 1 image and 1 wall of text, we want a large splash image in the background, with text at the bottom as a caption, that slowly cycles through the full story (switching images and captions as it goes). This can be done by splitting the current story by every other period, and generating images for each of these sentences respectively. From there animating will need to be done to switch between images and text

**ETA: give a rough time estimate to complete this issue**

4-5 hours

**Additional Information?**

**Comment by khushijpatel** [comment]
Closing this issue since task is more involved given the time and need to focus on other tasks (testing). Task would require change in UI and a whole new set of tests, and a rework of the page so not implementing the feature.
