### ISSUE TITLE
Account for Refresh Rate

### ISSUE THREAD

**Issue by ShashankVenkatramani** [cse110-sp23-group16/cse110-sp23-group16#22]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

The animation loop in canvas on the sky map is updated based on the client refresh rate. As such, we need to modify the animate loop so that it doesnt trigger animations twice as fast on 120Hz monitors as opposed to the default 60hz.

**ETA: give a rough time estimate to complete this issue**

45 minutes to 2 hours

**Additional Information?**

Has not been done before by any team members, might require experimentation

**Comment by khushijpatel** [comment]
Closing this issue given the limited time and need to focus on other tasks.
