### ISSUE TITLE
Implement the Selection Feature

### ISSUE THREAD

**Issue by JGong7** [cse110-sp23-group16/cse110-sp23-group16#34]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

After 5 stars being chose:
- [x] Decide the constellation with most number of star selected 
- [x] Draw line between the constellation stars
- [x] Display constellation image
- [x] Display confirmation button and link to the next page

**ETA: give a rough time estimate to complete this issue**
1 to 2 days

**Additional Information?**

**Comment by ShashankVenkatramani** [comment]
Branch is merged, unsure why it didn't auto close. Closing the issue.
