### ISSUE TITLE
ci/cd pipeline 

### ISSUE THREAD

**Issue by VictorKuu** [cse110-sp23-group16/cse110-sp23-group16#50]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**
On Sunday, we are expected to present 3 deliverables: phase1.png - a diagram of your phase 1 build pipeline (can be phase1.drawio.png if using draw.io), phase1.md - a short 2 page (roughly) status on the pipeline in terms of what is currently functional (and what is planned or in progress). Embed your diagram in the markdown file, phase1.mp4 - a no more than 2 min video demonstration of the pipeline.

Khushi, Shashank, and I are developing the official webpage that explains our documentation. I finished the JsDoc portion, Shashank finished Prettier Linter JEST testing, Khushi finished Code Climate.

I also will finish the diagram, which is almost completed at the making of this time. 

The video will be done by <insert name>

- [ phase1.png ] feature 1
- [ phase1.md] feature 2
- [phase1.mp4 ] feature 3

**ETA: give a rough time estimate to complete this issue**

**Additional Information?**

**Comment by ShashankVenkatramani** [comment]
CI/CD Pipeline has been tracked with several other issues, and completed! Closing issue.
