### ISSUE TITLE
Broken Relational Link on the thank you page

### ISSUE THREAD

**Issue by ShashankVenkatramani** [cse110-sp23-group16/cse110-sp23-group16#62]
**Describe the bug**
It appears the thank you page has a hard link back to the landing page, rather than a relational link, and as such when deployed to github pages it breaks since it has an extra directory in the link by default. Change to a relational link to fix.

**To Reproduce**

1. Go to [thank you page](https://cse110-sp23-group16.github.io/cse110-sp23-group16/source/pages/thankyou_page/thankyou.html)
2. Click the "Back home to try another constellation"

**Expected behavior**
Should take me back to a landing page, instead is an error 404

**Screenshots**
n/a

**Desktop (please complete the following information):**

Error persists regardless of device

**Smartphone (please complete the following information):**

Error persists regardless of device

**Additional context**
n/a

**Comment by ChiSWong** [comment]
Good finding, I will get that later
