### ISSUE TITLE
Organize skymap code

### ISSUE THREAD

**Issue by sorata000x** [cse110-sp23-group16/cse110-sp23-group16#69]
**Give a detailed description on the tasks and lay out each expectation for that task in a clear and concise manner**

Organize skymap codes to make them easier to read and use though:
 - Avoid using var and global variables by passing function parameters or convert to class variable
 - Put everything into functions
 - Avoid repeating codes

30 minutes

**Comment by ChiSWong** [comment]
Don't focus too much on refactoring the code, prioritize functionality over maintainability
